### PR TITLE
add db.sync () method, allows users to call in order to prevent loss of data.

### PR DESCRIPTION
**Pull request by wjw465150**
add db.sync () method, allows users to call in order to prevent loss of data.

### CODE REVIEW

**Comment by jankotek** [comment]
I checked sync() method with disabled transactions mode and I found possible error. Buffer.force() was not called before DB with disabled transactions was closed.

But I am not going to integrate this patch. DB has cache for unwritten data and calling sync() would provide false sense of security, since data were not written into file yet. Also with disabledTransactions store may get corrupted even with sync() called after every write (only some of dirty pages will be written before crash).

**Comment by wjw465150** [comment]
In disableTransactions environment, when the program terminates abnormally , this will lose data, how to solve it?

**Comment by jankotek** [comment]
> In disableTransactions environment, when the program terminates abnormally , this will lose data, how to solve it?

Use transactions if you need to protect your data. Disabling transaction is designed for speed, not for protecting your data.

**Comment by wjw465150** [comment]
Use transactions Performance will drop a lot of ,In disableTransactions environment without losing data, how to do it?

**Comment by jankotek** [comment]
I would suggest moving to other universe where physical law does not apply.

**Comment by xdylxdyl** [comment]
i use guava of google
    <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>11.0.1</version>
        </dependency>

.i use HashBasedTable. and put it in a hashMap.

but when i commit it then get it again,it tell me a null point error.

can jdbm save HashBasedTable?

**Pull request closed without merging**
